version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
  redis:
    image: bitnami/redis
    volumes:
      - ./redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
