duration: 10
protoPath: ../proto/helloworld.proto
serviceName: Greeter
packageName: greeterPackage
methodName: sayHello
payloadPath: ../load-test-engine/load-test-config/payload.js
callbackPath: ../load-test-engine/load-test-config/callback.js
